data<-read.csv(file.choose(),sep = ",",header = "TRUE")
View(data)
attach(data)
print("Y is dependent variable")
mod2<-lm(Y~X,data=data)
print(mod2)
print("X is dependent variable")
mod1<-lm(X~Y,data=data)
print(mod1)
